HMAFlex/Controllers/EveningClassController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using HMAFlex.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HMAFlex.Controllers
{
    public class EveningClassController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult Expiration()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult UpdateTrials()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult UpcomingTrials()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult Members()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult TrialLessons()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Message = id;

            return View();
        }

        [HttpPost]
        public IActionResult EditStudent(IFormCollection editForm)
        {
            int id = Int32.Parse(editForm["Id"]);
            EveningClassStudent student = Util.GetEveningClassStudent(id);

            foreach (var (key, value) in editForm)
            {
                if (key != "__RequestVerificationToken" && value != "")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "MembershipExpiration":
                            student.MembershipExpiration = DateTime.Parse(value);
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "Email":
                            student.Email = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);
                            break;
                        case "Status":
                            student.Status = Util.GetEveningProgram(value);
                            break;
                        case "ContactOne":
                            student.ContactOne = value;
                            break;
                        case "RelationOne":
                            student.RelationOne = value;
                            break;
                        case "PhoneOne":
                            student.PhoneOne = value;
                            break;
                        case "ContactTwo":
                            student.ContactTwo = value;
                            break;
                        case "RelationTwo":
                            student.RelationTwo = value;
                            break;
                        case "PhoneTwo":
                            student.PhoneTwo = value;
                            break;
                        case "ContactThree":
                            student.ContactThree = value;
                            break;
                        case "RelationThree":
                            student.RelationThree = value;
                            break;
                        case "PhoneThree":
                            student.PhoneThree = value;
                            break;
                    }

                    student = Util.GetEveningClassStudent(id);
                }
            }
            return RedirectToAction("Index");
        }
        

    [HttpGet]
        public IActionResult DeleteStudent(int id)
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Message = id;
            return View();
        }

        [HttpPost]
        public IActionResult DeleteStudent(IFormCollection form)
        {
            int id = Int32.Parse(form["Id"]);
            
            Program.DB.Remove(id, "EveningClassStudents");
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateStudent()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public IActionResult CreateStudent(IFormCollection newStudent)
        {
            EveningClassStudent student = new EveningClassStudent();
            student = Program.EveningClassStudents.Last().Value;

            foreach (var (key, value) in newStudent)
            {
                if (key != "__RequestVerificationToken")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "MembershipExpiration":
                            student.MembershipExpiration = DateTime.Parse(value);
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "Email":
                            student.Email = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);
                            break;
                        case "Status":
                            student.Status = Util.GetEveningProgram(value);
                            break;
                        case "ContactOne":
                            student.ContactOne = value;
                            break;
                        case "RelationOne":
                            student.RelationOne = value;
                            break;
                        case "PhoneOne":
                            student.PhoneOne = value;
                            break;
                        case "ContactTwo":
                            student.ContactTwo = value;
                            break;
                        case "RelationTwo":
                            student.RelationTwo = value;
                            break;
                        case "PhoneTwo":
                            student.PhoneTwo = value;
                            break;
                        case "ContactThree":
                            student.ContactThree = value;
                            break;
                        case "RelationThree":
                            student.RelationThree = value;
                            break;
                        case "PhoneThree":
                            student.PhoneThree = value;
                            break;
                    }

                    student = Program.EveningClassStudents.Last().Value;
                }
            }

            UserActionLog.AddEvent(Util.GetWebUser(Int32.Parse(HttpContext.Session.GetString("loggedInUser"))), "Create Evening Class Student - " + student.FirstName + " " + student.LastName + " (" + student.Id + ")");

            return RedirectToAction("Index");
        }

HMAFlex/Views/EveningClass/DeleteStudent.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Delete Evening Class Student";
    int id = ViewBag.Message;

    EveningClassStudent student = Util.GetEveningClassStudent(id);
}
<style>
    .confirmDelete {
        margin: 0 auto !important;
    }
</style>
<h1>Delete Evening Class Student</h1>
@{
    <div class="confirmDelete">
        <h3>Are you sure that you would like to delete student @student.FirstName @student.LastName?</h3>
        <form method="POST">
            <div class="row">
                <div class="col-2">
                    <label for="id">ID</label>
                    <input type="text" style="text-align: center;" class="form-control form-control-user" id="id" readonly aria-describedby="id" value="@student.Id" name="Id">
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-2">
                    <input type="submit" style="color: white !important;" class="btn btn-primary btn-user btn-block">
                </div>
            </div>
        </form>
    </div>
}

HMAFlex/Views/EveningClass/DetailStudent.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    Layout = "_GeneralLayout";
    ViewData["Title"] = "Evening Class Student Details";
    int id = ViewBag.Message;

    EveningClassStudent student = Util.GetEveningClassStudent(id);
}
<!--
Student Information
Medical Information
Pickup Information
-->
@{
    <h1>EveningClass Student Details - ID: @student.Id (@student.LastName, @student.FirstName)</h1>

    <div class="row" style="text-align: center;">
        <div class="col-3">
            @Html.ActionLink("Edit Student", "EditStudent", "EveningClass", new {Id = id})
        </div>
        <div class="col-3">
            @Html.ActionLink("Print TKD Certificate", "PrintCertificate", "EveningClass", new {Id = id, Type = "Taekwondo - Student"})
        </div>
        <div class="col-3">
            @Html.ActionLink("Print Judo Certificate", "PrintCertificate", "EveningClass", new {Id = id, Type = "Judo - Student"})
        </div>
        <div class="col-3">
            @Html.ActionLink("Delete Student", "DeleteStudent", "EveningClass", new {Id = id})
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">
                            <div class="hma-logo">
                                <img src="~/img/condensedlogo.png" width="100%">
                            </div>
                            <div class="basic-info">
                                <div class="text-xl-center text-uppercase font-weight-bold">
                                    <h2>@student.FirstName @student.LastName</h2></div>
                                <div class="text-lg-center"><b>Student Since:</b> @student.JoinDate</div>
                                <div class="text-lg-center"><b>Course Type:</b> @student.CourseType</div>
                                <div class="text-lg-center"><b>Membership Expiration:</b> @student.MembershipExpiration.ToShortDateString()</div>
                                <div class="text-lg-center"><b>Status:</b> @Util.GetEveningProgramString(student.Status)</div>
                                <div class="text-lg-center"><b>Active?</b> @student.CurrentStudent</div>
                            </div>
                        </div>
                        <div class="col-8" style="border-left: 1px solid #a9aab1; padding-left: 10px;">
                            <div class="text-xl-center text-uppercase font-weight-bold">General Information</div>
                            <div class="text-lg-left"><b>Taekwondo Belt:</b> @Util.GetRankString(student.TaekwondoRank)</div>
                            <div class="text-lg-left"><b>Judo Belt:</b> @Util.GetRankString(student.JudoRank)</div>
                            <div class="text-lg-left"><b>Birthday:</b> @student.Birthday.ToShortDateString</div>
                            <div class="text-lg-left"><b>Email:</b> @student.Email</div>
                            <div class="text-lg-left"><b>Address:</b> @student.Address</div>

                            <br/>

                            <div class="text-xl-center text-uppercase font-weight-bold">Contact Information</div>
                            <div class="row">
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Name</div>
                                    <div class="text-lg-center">@student.ContactOne</div>
                                    <div class="text-lg-center">@student.ContactTwo</div>
                                    <div class="text-lg-center">@student.ContactThree</div>
                                </div>
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Relation</div>
                                    <div class="text-lg-center">@student.RelationOne</div>
                                    <div class="text-lg-center">@student.RelationTwo</div>
                                    <div class="text-lg-center">@student.RelationThree</div>
                                </div>
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Phone Number</div>
                                    <div class="text-lg-center">@student.PhoneOne</div>
                                    <div class="text-lg-center">@student.PhoneTwo</div>
                                    <div class="text-lg-center">@student.PhoneThree</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

HMAFlex/Views/EveningClass/Expiration.cshtml
@using System.Collections
@using System.Xml
@{
    Layout = "_GeneralLayout";

    var sortedValues = Program.EveningClassStudents.Values.OrderBy(student => student.MembershipExpiration);
}

<h1>Membership Expirations</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Evening Class Expirations</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>CourseType</th>
                    <th>Active</th>
                    <th>Expiration Date</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach (EveningClassStudent student in sortedValues)
                    {
                        <tr>
                            <td>@student.Id</td>
                            <td>@student.FirstName @student.LastName</td>
                            <td>@student.CourseType</td>
                            <td>@student.CurrentStudent</td>
                            <td>@student.MembershipExpiration.ToShortDateString()</td>
                            <td>
                                @Html.ActionLink("Edit", "EditStudent", "EveningClass", new {Id = student.Id}) |
                                @Html.ActionLink("Details", "DetailStudent", "EveningClass", new {Id = student.Id}) |
                                @Html.ActionLink("Delete", "DeleteStudent", "EveningClass", new {Id = student.Id})</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

HMAFlex/Views/EveningClass/Index.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Evening Class Students";
}
<h1>Evening Class Students</h1>
<p>
  @Html.ActionLink("Create New", "CreateStudent", "EveningClass")
</p>
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Evening Class Students</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Taekwondo Belt Rank</th>
                      <th>Judo Belt Rank</th>
                      <th>Status</th>
                      <th>Course Type</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  @{
                    foreach (var (key, student) in Program.EveningClassStudents)
                    {
                      <tr>
                        <td>@student.Id</td>
                        <td>@student.FirstName @student.LastName</td>
                        <td>@Util.GetRankString(student.TaekwondoRank)</td>
                        <td>@Util.GetRankString(student.JudoRank)</td>
                        <td>@student.CourseType</td>
                        <td>@Util.GetEveningProgramString(student.Status)</td>
                        <td>
                          @Html.ActionLink("Edit", "EditStudent", "EveningClass", new {Id = student.Id}) |
                          @Html.ActionLink("Details", "DetailStudent", "EveningClass", new {Id = student.Id}) |
                          @Html.ActionLink("Delete", "DeleteStudent", "EveningClass", new {Id = student.Id})<br/>
                          @Html.ActionLink("Print TKD Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Taekwondo - Student"}) |
                          @Html.ActionLink("Print Judo Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Judo - Student"})</td>
                      </tr>
                    }
                  }
                  </tbody>
                </table>
              </div>
            </div>
          </div>

HMAFlex/Views/EveningClass/Members.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Evening Class Members";
}
<h1>Evening Class Members</h1>
<p>
  @Html.ActionLink("Create New", "CreateStudent", "EveningClass")
</p>
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Evening Class Students</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Taekwondo Belt Rank</th>
                      <th>Judo Belt Rank</th>
                      <th>Status</th>
                      <th>Course Type</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  @{
                    foreach (var (key, student) in Program.EveningClassStudents)
                    {
                      if (student.Status != EveningClassProgram.TrialLesson)
                      {
                        <tr>
                          <td>@student.Id</td>
                          <td>@student.FirstName @student.LastName</td>
                          <td>@Util.GetRankString(student.TaekwondoRank)</td>
                          <td>@Util.GetRankString(student.JudoRank)</td>
                          <td>@Util.GetEveningProgramString(student.Status)</td>
                          <td>@student.CourseType</td>
                          <td>
                            @Html.ActionLink("Edit", "EditStudent", "EveningClass", new {Id = student.Id}) |
                            @Html.ActionLink("Details", "DetailStudent", "EveningClass", new {Id = student.Id}) |
                            @Html.ActionLink("Delete", "DeleteStudent", "EveningClass", new {Id = student.Id})<br/>
                            @Html.ActionLink("Print TKD Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Taekwondo - Student"}) |
                            @Html.ActionLink("Print Judo Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Judo - Student"})</td>
                        </tr>
                      }
                    }
                  }
                  </tbody>
                </table>
              </div>
            </div>
          </div>

HMAFlex/Views/EveningClass/PrintCertificate.cshtml
@using System.Xml
@using Api2PdfLibrary
@using HMAFlex.Controllers
@using Microsoft.VisualBasic
@{
    
    XmlReader configManager = XmlReader.Create("Views/Shared/Configuration.xml");
    
    Layout = "_GeneralLayout";
    ViewData["Title"] = "Evening Class Belt Certificate";
    int id = ViewBag.Message;
    string viewbagType = ViewBag.Type;
    string testType = viewbagType.Split(" - ")[0];
    string userType = viewbagType.Split(" - ")[1];
    string date = "";
    
    while (configManager.Read())
    {
        if (configManager.NodeType == XmlNodeType.Element && configManager.Name == "ConfigManager")
        {
            if (configManager.HasAttributes)
            {
                if (testType == "Taekwondo")
                {
                    date = configManager.GetAttribute("TaekwondoTestingDate");
                }
                if (testType == "Judo")
                {
                    date = configManager.GetAttribute("JudoTestingDate");
                }
            }
        }
    }

    string belt = "";
    string testerName = "";
    string nextBelt = "";

    var taekwondoBelts = new Dictionary<int, string>();
    taekwondoBelts.Add(0 ,"None");
    taekwondoBelts.Add(1 ,"White Belt");
    taekwondoBelts.Add(2 ,"Yellow Belt");
    taekwondoBelts.Add(3 ,"Orange Belt");
    taekwondoBelts.Add(4 ,"Green Belt");
    taekwondoBelts.Add(5 ,"Blue-Tip Belt");
    taekwondoBelts.Add(6 ,"Blue Belt");
    taekwondoBelts.Add(7 ,"Purple Belt");
    taekwondoBelts.Add(8 ,"Brown Belt");
    taekwondoBelts.Add(9 ,"Red Belt");
    taekwondoBelts.Add(10 ,"Black-Tip Belt");
    taekwondoBelts.Add(11 ,"Tiger Belt");
    taekwondoBelts.Add(12 ,"Dragon Belt");
    taekwondoBelts.Add(13 ,"Temporary Black Belt");
    taekwondoBelts.Add(14 ,"First Dan");
    taekwondoBelts.Add(15 ,"Second Dan");
    taekwondoBelts.Add(16 ,"Third Dan");
    taekwondoBelts.Add(17 ,"Fourth Dan");
    taekwondoBelts.Add(18 ,"Fifth Dan");
    taekwondoBelts.Add(19 ,"Sixth Dan");

    var judoBelts = new Dictionary<int, string>();
    judoBelts.Add(0 ,"None");
    judoBelts.Add(1 ,"White Belt");
    judoBelts.Add(2 ,"Yellow Belt");
    judoBelts.Add(3 ,"Orange Belt");
    judoBelts.Add(4 ,"Green Belt");
    judoBelts.Add(5 ,"Blue Belt");
    judoBelts.Add(6 ,"Purple Belt");
    judoBelts.Add(7 ,"Brown Belt");
    judoBelts.Add(8 ,"Red Belt");
    judoBelts.Add(9 ,"Temporary Black Belt");
    judoBelts.Add(10 ,"First Dan");
    judoBelts.Add(11 ,"Second Dan");
    judoBelts.Add(12 ,"Third Dan");
}
@{
    /*
    * https://localhost:5001/HtmlLayouts/ColorBeltTest
    */

    ViewData["Title"] = testType + " Certificate";
    var link = "http://www.hmalouisville.com";
    var fileName = testType + "Certificate - " + testerName + " - " + DateAndTime.DateString + ".pdf";

    var options = new Dictionary<string, string>();
    options.Add("orientation", "portrait");
    options.Add("pageSize", "Letter");

    var a2pClient = new Api2Pdf("0e376dff-1081-4e59-a152-4fd73a540357");
    var apiResponseViewer = a2pClient.WkHtmlToPdf.FromUrl(link, inline: true, outputFileName: fileName, options);
    var apiResponseDownload = a2pClient.WkHtmlToPdf.FromUrl(link, inline: false, outputFileName: fileName, options);
}
@{
    XmlReader xmlReader = XmlReader.Create("Views/EveningClass/EveningClassStudent.xml");

    while (xmlReader.Read())
    {
        if (xmlReader.NodeType == XmlNodeType.Element && xmlReader.Name == userType)
        {
            if (xmlReader.HasAttributes)
            {
                if (xmlReader.GetAttribute("Id") == id.ToString())
                {
                    belt = xmlReader.GetAttribute(testType + "BeltRank");
                    if (testType == "Taekwondo")
                    {
                        foreach (var (beltId, beltName) in taekwondoBelts)
                        {
                            if (beltName == belt)
                            {
                                nextBelt = taekwondoBelts[beltId + 1];
                            }
                        }
                    }
                    else
                    {
                        foreach (var (beltId, beltName) in judoBelts)
                        {
                            if (beltName == belt)
                            {
                                nextBelt = judoBelts[beltId + 1];
                            }
                        }
                    }

                    testerName = xmlReader.GetAttribute("FirstName") + " " + xmlReader.GetAttribute("LastName");

                    Util.UpdateBeltTestCertificate(id, testerName, date, testType, nextBelt);
                    
                    XmlDocument xmlDocument = new XmlDocument();
                    xmlDocument.Load("Views/EveningClass/EveningClassStudent.xml");
                    XmlNodeList students = xmlDocument.SelectNodes("/EveningClass/" + userType);
                    
                    foreach (XmlNode student in students)
                    {
                        if (student.Attributes["Id"].Value.Equals(id.ToString()))
                        {
                            student.Attributes[testType + "BeltRank"].InnerText = nextBelt;
                        }
                    }
                    xmlDocument.Save("Views/EveningClass/EveningClassStudent.xml");

                    <h1>@testType Belt Test Certificate</h1>
                    <h2>@testerName (@belt -> @nextBelt)</h2>

                    <div class="row">
                        <div class="col-3">

                        </div>
                        <div class="col-3">
                            <a class="btn btn-secondary btn-user btn-block" href="@apiResponseDownload.Pdf"><i class="fas fa-fw fa-download"></i> &nbsp;Download</a>
                        </div>
                        <div class="col-3">
                            <a class="btn btn-secondary btn-user btn-block" href="@apiResponseViewer.Pdf"><i class="fas fa-fw fa-print"></i> &nbsp;Print</a>
                        </div>
                        <div class="col-3">

                        </div>
                    </div>
                    <br/>
                    <div id="adobe-dc-view">
                        <embed src="@apiResponseViewer.Pdf" type="application/pdf" width="100%" height="600px"/>
                    </div>
                }
            }
        }
    }
}

HMAFlex/Views/EveningClass/TrialLessons.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Evening Class Trial Lessons";
}
<h1>Evening Class Trial Lessons</h1>
<p>
  @Html.ActionLink("Create New", "CreateStudent", "EveningClass")
</p>
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Trial Lesson Students</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Taekwondo Belt Rank</th>
                      <th>Judo Belt Rank</th>
                      <th>Status</th>
                      <th>Course Type</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  @{
                    foreach (var (key, student) in Program.EveningClassStudents)
                    {
                      <tr>
                        <td>@student.Id</td>
                        <td>@student.FirstName @student.LastName</td>
                        <td>@Util.GetRankString(student.TaekwondoRank)</td>
                        <td>@Util.GetRankString(student.JudoRank)</td>
                        <td>@Util.GetEveningProgramString(student.Status)</td>
                        <td>@student.CourseType</td>
                        <td>
                          @Html.ActionLink("Edit", "EditStudent", "EveningClass", new {Id = student.Id}) |
                          @Html.ActionLink("Details", "DetailStudent", "EveningClass", new {Id = student.Id}) |
                          @Html.ActionLink("Delete", "DeleteStudent", "EveningClass", new {Id = student.Id})<br/>
                          @Html.ActionLink("Print TKD Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Taekwondo - Student"}) |
                          @Html.ActionLink("Print Judo Cert.", "PrintCertificate", "EveningClass", new {Id = student.Id, Type = "Judo - Student"})</td>
                      </tr>
                    }
                  }
                  </tbody>
                </table>
              </div>
            </div>
          </div>