HMAFlex/Controllers/SummerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using HMAFlex.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HMAFlex.Controllers
{
    public class SummerController : Controller
    {
        
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        public IActionResult PrintAttendance()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        public IActionResult EmergencyContact()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public IActionResult Staff()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        [HttpGet]
        public IActionResult CreateStudent()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        [HttpPost]
        public IActionResult CreateStudent(IFormCollection newStudent)
        {
            SummerStudent student = new SummerStudent();
            student = Program.SummerStudents.Last().Value;

            foreach (var (key, value) in newStudent)
            {
                if (key != "__RequestVerificationToken")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "PhysicianName":
                            student.PhysicianName = value;
                            break;
                        case "PhysicianExt":
                            student.PhysicianExt = value;
                            break;
                        case "PhysicianNumber":
                            student.PhysicianNumber = value;
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "School":
                            student.School = value;
                            break;
                        case "HospitalPref":
                            student.HospitalPref = value;
                            break;
                        case "HospitalExt":
                            student.HospitalExt = value;
                            break;
                        case "HospitalPhone":
                            student.HospitalPhone = value;
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "HealthConditions":
                            student.HealthConditions = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Medication":
                            student.Medication = value;
                            break;
                        case "Allergies":
                            student.Allergies = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);
                            break;
                        case "MembershipExpiration":
                            student.MembershipExpiration = DateTime.Parse(value);
                            break;
                        case "PickupOne":
                            student.PickupOne = value;
                            break;
                        case "RelationOne":
                            student.RelationOne = value;
                            break;
                        case "CellOne":
                            student.CellOne = value;
                            break;
                        case "PickupTwo":
                            student.PickupTwo = value;
                            break;
                        case "RelationTwo":
                            student.RelationTwo = value;
                            break;
                        case "CellTwo":
                            student.CellTwo = value;
                            break;
                        case "PickupThree":
                            student.PickupThree = value;
                            break;
                        case "RelationThree":
                            student.RelationThree = value;
                            break;
                        case "CellThree":
                            student.CellThree = value;
                            break;
                        case "PickupFour":
                            student.PickupFour = value;
                            break;
                        case "RelationFour":
                            student.RelationFour = value;
                            break;
                        case "CellFour":
                            student.CellFour = value;
                            break;
                    }
                    
                    student = Program.SummerStudents.Last().Value;
                }
            }

            UserActionLog.AddEvent(Util.GetWebUser(Int32.Parse(HttpContext.Session.GetString("loggedInUser"))), "Create Summer Student - " + student.FirstName + " " + student.LastName + " (" + student.Id + ")");
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Message = id;
            
            return View();
        }

        [HttpPost]
        public IActionResult EditStudent(IFormCollection editForm)
        {
            int id = Int32.Parse(editForm["Id"]);
            SummerStudent student = Util.GetSummerStudent(id);
            
            IDictionary<string, string> editedValues = new Dictionary<string, string>();
            foreach (var (key, value) in editForm)
            {
                if (key != "__RequestVerificationToken" || value != "")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "PhysicianName":
                            student.PhysicianName = value;
                            break;
                        case "PhysicianExt":
                            student.PhysicianExt = value;
                            break;
                        case "PhysicianNumber":
                            student.PhysicianNumber = value;
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "School":
                            student.School = value;
                            break;
                        case "HospitalPref":
                            student.HospitalPref = value;
                            break;
                        case "HospitalExt":
                            student.HospitalExt = value;
                            break;
                        case "HospitalPhone":
                            student.HospitalPhone = value;
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "HealthConditions":
                            student.HealthConditions = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Medication":
                            student.Medication = value;
                            break;
                        case "Allergies":
                            student.Allergies = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);

HMAFlex/Views/Summer/DeleteStaff.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Delete Summer Staff";
    int id = ViewBag.Message;
    SummerStaff staff = Util.GetSummerStaff(id);
}
<style>
    .confirmDelete {
        margin: 0 auto !important;
    }
</style>
<h1>Delete Summer Staff</h1>
@{
    <div class="confirmDelete">
        <h3>Are you sure that you would like to delete staff member @staff.FirstName @staff.LastName?</h3>
        <form method="POST">
            <div class="row">
                <div class="col-2">
                    <label for="id">ID</label>
                    <input type="text" style="text-align: center;" class="form-control form-control-user" id="id" readonly aria-describedby="id" value="@staff.Id" name="Id">
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-2">
                    <input type="submit" style="color: white !important;" class="btn btn-primary btn-user btn-block">
                </div>
            </div>
        </form>
    </div>
}

HMAFlex/Views/Summer/DeleteStudent.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Delete Summer Student";
    int id = ViewBag.Message;
    SummerStudent student = Util.GetSummerStudent(id);
}
<style>
    .confirmDelete {
        margin: 0 auto !important;
    }
</style>
<h1>Delete Summer Student</h1>
@{
    <div class="confirmDelete">
        <h3>Are you sure that you would like to delete student @student.FirstName @student.LastName?</h3>
        <form method="POST">
            <div class="row">
                <div class="col-2">
                    <label for="id">ID</label>
                    <input type="text" style="text-align: center;" class="form-control form-control-user" id="id" readonly aria-describedby="id" value="@student.Id" name="Id">
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-2">
                    <input type="submit" style="color: white !important;" class="btn btn-primary btn-user btn-block">
                </div>
            </div>
        </form>
    </div>
}

HMAFlex/Views/Summer/DetailStaff.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    Layout = "_GeneralLayout";
    ViewData["Title"] = "Summer Camp Staff Details";
    int id = ViewBag.Message;
    SummerStaff staff = Util.GetSummerStaff(id);
}
<!--
GeneralInformation
Camp Day Information
-->
@{
                    <h1>Summer Camp Staff Details - ID: @staff.Id (@staff.LastName, @staff.FirstName)</h1>
                    
                    <div class="row" style="text-align: center;">
                        <div class="col-4">
                            @Html.ActionLink("Edit Staff", "EditStaff", "Summer", new {Id = id})
                        </div>
                        <div class="col-4">
                            @Html.ActionLink("Print TKD Certificate", "PrintCertificate", "Summer", new {Id = id, Type = "Taekwondo - StaffMember"})
                        </div>
                        <div class="col-4">
                            @Html.ActionLink("Delete Staff", "DeleteStaff", "Summer", new {Id = id})
                        </div>
                    </div>                                                           
                                                                               
    <div class="row">
        <div class="col-12">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">
                            <div class="hma-logo">
                                <img src="~/img/condensedlogo.png" width="100%">
                            </div>
                            <div class="basic-info">
                                <div class="text-xl-center text-uppercase font-weight-bold"><h2>@staff.FirstName @staff.LastName</h2></div>
                                <div class="text-lg-center"><b>Taekwondo Belt:</b> @staff.TaekwondoRank</div>
                            </div>
                        </div>
                        <div class="col-8" style="border-left: 1px solid #a9aab1; padding-left: 10px;">
                            <div class="text-xl-center text-uppercase font-weight-bold">General Information</div>
                            <div class="text-lg-left"><b>Birthday:</b> @staff.Birthday.ToShortDateString</div>
                            <div class="text-lg-left"><b>Email:</b> @staff.Email</div>
                            <div class="text-lg-left"><b>Phone Number:</b> @staff.PhoneNumber</div>
                                            
                            <br/>
                                            
                            <div class="text-xl-center text-uppercase font-weight-bold">Daily Summer Camp Information</div>
                            <div class="row">
                                <div class="col-1">
                                    &nbsp;
                                </div>
                                <div class="col-2">
                                    <div class="text-lg-center font-weight-bold">Monday?</div>
                                    @{
                                        if (staff.Monday)
                                        {
                                            <img src="~/img/checkmark.png" width="100%" alt="True">
                                        }
                                    }
                                </div>
                                <div class="col-2">
                                    <div class="text-lg-center font-weight-bold">Tuesday?</div>
                                    @{
                                        if (staff.Tuesday)
                                        {
                                            <img src="~/img/checkmark.png" width="100%" alt="True">
                                        }
                                    }
                                </div>
                                <div class="col-2">
                                    <div class="text-lg-center font-weight-bold">Wednesday?</div>
                                    @{
                                        if (staff.Wednesday)
                                        {
                                            <img src="~/img/checkmark.png" width="100%" alt="True">
                                        }
                                    }
                                </div>
                                <div class="col-2">
                                    <div class="text-lg-center font-weight-bold">Thursday?</div>
                                    @{
                                        if (staff.Thursday)
                                        {
                                            <img src="~/img/checkmark.png" width="100%" alt="True">
                                        }
                                    }
                                </div>
                                <div class="col-2">
                                    <div class="text-lg-center font-weight-bold">Friday?</div>
                                    @{
                                        if (staff.Friday)
                                        {
                                            <img src="~/img/checkmark.png" width="100%" alt="True">
                                        }
                                    }
                                </div>
                                <div class="col-1">
                                    &nbsp;
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

HMAFlex/Views/Summer/DetailStudent.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
    Layout = "_GeneralLayout";
    ViewData["Title"] = "Summer Camp Student Details";
    int id = ViewBag.Message;
    SummerStudent student = Util.GetSummerStudent(id);
}
<!--
Student Information
Medical Information
Pickup Information
-->
@{
    <h1>Summer Camp Student Details - ID: @student.Id (@student.LastName, @student.FirstName)</h1>
                    
    <div class="row" style="text-align: center;">
        <div class="col-3">
            @Html.ActionLink("Edit Student", "EditStudent", "Summer", new {Id = id})
        </div>
        <div class="col-3">
            @Html.ActionLink("Print TKD Certificate", "PrintCertificate", "Summer", new {Id = id, Type = "Taekwondo - Student"})
        </div>
        <div class="col-3">
            @Html.ActionLink("Print Judo Certificate", "PrintCertificate", "Summer", new {Id = id, Type = "Judo - Student"})
        </div>
        <div class="col-3">
            @Html.ActionLink("Delete Student", "DeleteStudent", "Summer", new {Id = id})
        </div>
    </div>                                                          
                                                                               
    <div class="row">
        <div class="col-12">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">
                            <div class="hma-logo">
                                <img src="~/img/condensedlogo.png" width="100%">
                            </div>
                            <div class="basic-info">
                                <div class="text-xl-center text-uppercase font-weight-bold"><h2>@student.FirstName) @student.LastName</h2></div>
                                <div class="text-lg-center"><b>Student Since:</b> @student.JoinDate.ToShortDateString</div>
                                <div class="text-lg-center"><b>Course Type:</b> @student.CourseType</div>
                                <div class="text-lg-center"><b>Membership Expiration:</b> @student.MembershipExpiration.ToShortDateString()</div>
                                <div class="text-lg-center"><b>Active?</b> @student.CurrentStudent</div>
                            </div>
                        </div>
                        <div class="col-8" style="border-left: 1px solid #a9aab1; padding-left: 10px;">
                            <div class="text-xl-center text-uppercase font-weight-bold">General Information</div>
                            <div class="text-lg-left"><b>School:</b> @student.School</div>
                            <div class="text-lg-left"><b>Birthday:</b> @student.Birthday.ToShortDateString()</div>
                            <div class="text-lg-left"><b>Address:</b> @student.Address</div>
                            <div class="text-lg-left"><b>Taekwondo Belt:</b> @Util.GetRankString(student.TaekwondoRank)</div>
                            <div class="text-lg-left"><b>Judo Belt:</b> @Util.GetRankString(student.JudoRank)</div>
                                            
                            <br/>
                                            
                            <div class="text-xl-center text-uppercase font-weight-bold">Medical Information</div>
                            <div class="text-lg-left"><b>Preferred Physician:</b> @student.PhysicianName</div>
                            <div class="text-lg-left"><b>Physician Number:</b> @student.PhysicianNumber  <b>Ext:</b> @student.PhysicianExt</div>
                            <div class="text-lg-left"><b>Preferred Hospital:</b> @student.HospitalPref</div>
                            <div class="text-lg-left"><b>Hospital Number:</b> @student.HospitalPhone <b>Ext:</b> @student.HospitalExt</div>
                            <div class="text-lg-left"><b>Condition(s):</b> @student.HealthConditions</div>
                            <div class="text-lg-left"><b>Allergies:</b> @student.Allergies</div>
                            <div class="text-lg-left"><b>Medication:</b> @student.Medication</div>
                                            
                            <br/>
                                            
                            <div class="text-xl-center text-uppercase font-weight-bold">Pickup Information</div>
                            <div class="row">
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Name</div>
                                    <div class="text-lg-center">@student.PickupOne</div>
                                    <div class="text-lg-center">@student.PickupTwo</div>
                                    <div class="text-lg-center">@student.PickupThree</div>
                                    <div class="text-lg-center">@student.PickupFour</div>
                                </div>
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Relation</div>
                                    <div class="text-lg-center">@student.RelationOne</div>
                                    <div class="text-lg-center">@student.RelationTwo</div>
                                    <div class="text-lg-center">@student.RelationThree</div>
                                    <div class="text-lg-center">@student.RelationFour</div>
                                </div>
                                <div class="col-4">
                                    <div class="text-lg-center font-weight-bold">Phone Number</div>
                                    <div class="text-lg-center">@student.CellOne</div>
                                    <div class="text-lg-center">@student.CellTwo</div>
                                    <div class="text-lg-center">@student.CellThree</div>
                                    <div class="text-lg-center">@student.CellFour</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

HMAFlex/Views/Summer/EmergencyContact.cshtml
@using Api2PdfLibrary
@using Microsoft.VisualBasic

@{
    /*
     * https://localhost:5001/HtmlLayouts/SummerEmergencyContact
     */
    
    ViewData["Title"] = "Summer Camp ICE";
    var link = "http://www.hmalouisville.com";
    var fileName = "Summer Camp ICE - " + DateAndTime.DateString + ".pdf";
    
    var options = new Dictionary<string, string>();
    options.Add("orientation", "landscape");
    options.Add("pageSize", "Letter");
    
    var a2pClient = new Api2Pdf("0e376dff-1081-4e59-a152-4fd73a540357");
    var apiResponseViewer = a2pClient.WkHtmlToPdf.FromUrl(link, inline: true, outputFileName: fileName, options);
    var apiResponseDownload = a2pClient.WkHtmlToPdf.FromUrl(link, inline: false, outputFileName: fileName, options);
}
<h1>Summer Camp Emergency Contact</h1>
<h2></h2>

<div class="row">
    <div class="col-3">
        
    </div>
    <div class="col-3">
        <a class="btn btn-secondary btn-user btn-block" href="@apiResponseDownload.Pdf"><i class="fas fa-fw fa-download"></i> &nbsp;Download</a>
    </div>
    <div class="col-3">
        <a class="btn btn-secondary btn-user btn-block" href="@apiResponseViewer.Pdf"><i class="fas fa-fw fa-print"></i> &nbsp;Print</a>
    </div>
    <div class="col-3">
        
    </div>
</div>
<br/>
<div id="adobe-dc-view">
    <embed src="@apiResponseViewer.Pdf" type="application/pdf" width="100%" height="600px" />
</div>

HMAFlex/Views/Summer/Index.cshtml
@using System.Xml
@using HMAFlex.Controllers
@{
  ViewData["Title"] = "Summer Students";
}
<link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<script>
$(document).ready( function () {
    $('#dataTable').DataTable();
} );
</script>
<h1>Summer Students</h1>
<p>
  @Html.ActionLink("Create New", "CreateStudent", "Summer")
</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Summer Students</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Belt Rank</th>
          <th>School</th>
          <th>Course Type</th>
          <th>Current Student</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @{
          foreach (var (key, student) in Program.SummerStudents)
          {
            <tr>
              <td>@student.Id</td>
              <td>@student.FirstName @student.LastName</td>
              <td>@Util.GetRankString(student.TaekwondoRank)</td>
              <td>@student.School</td>
              <td>@student.CourseType</td>
              <td>@student.CurrentStudent</td>
              <td>
                @Html.ActionLink("Edit", "EditStudent", "Summer", new {Id = student.Id}) |

                @Html.ActionLink("Details", "DetailStudent", "Summer", new {Id = student.Id}) |
                @Html.ActionLink("Delete", "DeleteStudent", "Summer", new {Id = student.Id}) <br/>
                @Html.ActionLink("Print TKD Cert.", "PrintCertificate", "Summer", new {Id = student.Id, Type = "Taekwondo - Student"}) |
                @Html.ActionLink("Print Judo Cert.", "PrintCertificate", "Summer", new {Id = student.Id, Type = "Judo - Student"})</td>
            </tr>
          }
        }
        </tbody>
      </table>
    </div>
  </div>
</div>

HMAFlex/Views/Summer/Staff.cshtml
@using HMAFlex.Controllers
@{
    ViewData["Title"] = "Summer Camp Staff Members";
}
<h1>Summer Camp Staff & Volunteer Information</h1>
<p>
  @Html.ActionLink("Create New", "CreateStaff", "Summer")
</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Summer Camp Staff Members</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Belt Rank</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @{
          foreach(var (key, staff) in Program.SummerStaff) {
            <tr>
              <td>@staff.Id</td>
              <td>@staff.FirstName @staff.LastName</td>
              <td>@Util.GetRankString(staff.TaekwondoRank)</td>
                            
              @{
                if (staff.Monday)
                {
                  <td><img src="~/img/checkmark.png" height="30px" width=auto></td>
                }
                else
                {
                  <td> </td>
                }
                if (staff.Tuesday)
                {
                  <td><img src="~/img/checkmark.png" height="30px" width=auto></td>
                }
                else
                {
                  <td> </td>
                }
                if (staff.Wednesday)
                {
                  <td><img src="~/img/checkmark.png" height="30px" width=auto></td>
                }
                else
                {
                  <td> </td>
                }
                if (staff.Thursday)
                {
                  <td><img src="~/img/checkmark.png" height="30px" width=auto></td>
                }
                else
                {
                  <td> </td>
                }
                if (staff.Friday)
                {
                  <td><img src="~/img/checkmark.png" height="30px" width=auto></td>
                }
                else
                {
                  <td> </td>
                }
              }
              <td>
                @Html.ActionLink("Edit", "EditStaff", "Summer", new { Id = staff.Id }) |

                @Html.ActionLink("Details", "DetailStaff", "Summer", new { Id = staff.Id }) |
                @Html.ActionLink("Delete", "DeleteStaff", "Summer", new { Id = staff.Id}) <br/>
                @Html.ActionLink("Print TKD Cert.", "PrintCertificate", "Summer", new {Id = staff.Id, Type = "Taekwondo - StaffMember"})</td>
            </tr>
          }
        }
        </tbody>
      </table>
    </div>
  </div>
</div>