HMAFlex/Models/CheckIn.cs
using System;
using System.Collections;
using System.Linq;
using HMAFlex.Controllers;

namespace HMAFlex.Models;

public class CheckIn
{
    private static string tableName;
    
    private int id; //checkinout log id
    private CheckInOutType type;
    private int sid; //student id
    private DateTime date;
    private DateTime time; //DateTime.Now.ToString("HH:mm:ss");

    public CheckIn(int id, CheckInOutType type, int sid, DateTime date, DateTime time)
    {
        tableName = "CheckInOut";
        
        this.id = id;
        this.type = type;
        this.sid = sid;
        this.date = date;
        this.time = time;

        if (this.id == 0)
        {
            ArrayList infoString = new ArrayList();
            infoString.Add(Util.CheckInOutTypeToString(type));
            infoString.Add(sid.ToString());
            infoString.Add(date.ToShortDateString());
            infoString.Add(time.ToString("HH:mm:ss"));
            infoString.Add("In");
        
            Program.DB.Insert(tableName,
                "Type, SID, Date, Time, InOut",
                string.Join(", ", infoString));
        }
    }

    public CheckIn()
    {
        tableName = "CheckInOut";

        id = 0;
        type = CheckInOutType.None;
        sid = 0;
        date = DateTime.Now;
        time = DateTime.Now;
        
        ArrayList infoString = new ArrayList();
        infoString.Add(Util.CheckInOutTypeToString(type));
        infoString.Add(sid.ToString());
        infoString.Add(date.ToShortDateString());
        infoString.Add(time.ToString("HH:mm:ss"));
        infoString.Add("In");

        Program.DB.Insert(tableName,
            "Type, SID, Date, Time, InOut",
            string.Join(", ", infoString));
    }

    public int Id => id;

    public CheckInOutType Type
    {
        get => type;
        set
        {
            type = value;
            Program.DB.Modify(id, tableName, "Type", Util.CheckInOutTypeToString(type));
        }
    }

    public int SID
    {
        get => sid;
        set
        {
            sid = value;
            Program.DB.Modify(id, tableName, "SID", sid.ToString());
        }
    }

    public DateTime Date
    {
        get => date;
        set
        {
            date = value;
            Program.DB.Modify(id, tableName, "Date", date.ToShortDateString());
        }
    }

    public DateTime Time
    {
        get => time;
        set
        {
            time = value;
            Program.DB.Modify(id, tableName, "Time", time.ToString("HH:mm:ss"));
        }
    }
}

HMAFlex/Controllers/AMPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using HMAFlex.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HMAFlex.Controllers
{
    public class AMPController : Controller
    {
        
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        public IActionResult PrintAttendance()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        public IActionResult EmergencyContact()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public IActionResult Staff()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        [HttpGet]
        public IActionResult CreateStudent()
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        
        [HttpPost]
        public IActionResult CreateStudent(IFormCollection newStudent)
        {
            AMPStudent student = new AMPStudent();
            student = Program.AMPStudents.Last().Value;

            foreach (var (key, value) in newStudent)
            {
                if (key != "__RequestVerificationToken")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "PhysicianName":
                            student.PhysicianName = value;
                            break;
                        case "PhysicianExt":
                            student.PhysicianExt = value;
                            break;
                        case "PhysicianNumber":
                            student.PhysicianNumber = value;
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "School":
                            student.School = value;
                            break;
                        case "HospitalPref":
                            student.HospitalPref = value;
                            break;
                        case "HospitalExt":
                            student.HospitalExt = value;
                            break;
                        case "HospitalPhone":
                            student.HospitalPhone = value;
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "HealthConditions":
                            student.HealthConditions = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Medication":
                            student.Medication = value;
                            break;
                        case "Allergies":
                            student.Allergies = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);
                            break;
                        case "MembershipExpiration":
                            student.MembershipExpiration = DateTime.Parse(value);
                            break;
                        case "PickupOne":
                            student.PickupOne = value;
                            break;
                        case "RelationOne":
                            student.RelationOne = value;
                            break;
                        case "CellOne":
                            student.CellOne = value;
                            break;
                        case "PickupTwo":
                            student.PickupTwo = value;
                            break;
                        case "RelationTwo":
                            student.RelationTwo = value;
                            break;
                        case "CellTwo":
                            student.CellTwo = value;
                            break;
                        case "PickupThree":
                            student.PickupThree = value;
                            break;
                        case "RelationThree":
                            student.RelationThree = value;
                            break;
                        case "CellThree":
                            student.CellThree = value;
                            break;
                        case "PickupFour":
                            student.PickupFour = value;
                            break;
                        case "RelationFour":
                            student.RelationFour = value;
                            break;
                        case "CellFour":
                            student.CellFour = value;
                            break;
                    }
                    
                    student = Program.AMPStudents.Last().Value;
                }
            }

            UserActionLog.AddEvent(Util.GetWebUser(Int32.Parse(HttpContext.Session.GetString("loggedInUser"))), "Create AMP Student - " + student.FirstName + " " + student.LastName + " (" + student.Id + ")");
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            if (HttpContext.Session.GetString("loggedIn") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Message = id;
            
            return View();
        }

        [HttpPost]
        public IActionResult EditStudent(IFormCollection editForm)
        {
            int id = Int32.Parse(editForm["Id"]);
            AMPStudent student = Util.GetAMPStudent(id);
            
            foreach (var (key, value) in editForm)
            {
                if (key != "__RequestVerificationToken" || value != "")
                {
                    switch (key)
                    {
                        case "FirstName":
                            student.FirstName = value;
                            break;
                        case "LastName":
                            student.LastName = value;
                            break;
                        case "PhysicianName":
                            student.PhysicianName = value;
                            break;
                        case "PhysicianExt":
                            student.PhysicianExt = value;
                            break;
                        case "PhysicianNumber":
                            student.PhysicianNumber = value;
                            break;
                        case "Birthday":
                            student.Birthday = DateTime.Parse(value);
                            break;
                        case "School":
                            student.School = value;
                            break;
                        case "HospitalPref":
                            student.HospitalPref = value;
                            break;
                        case "HospitalExt":
                            student.HospitalExt = value;
                            break;
                        case "HospitalPhone":
                            student.HospitalPhone = value;
                            break;
                        case "Address":
                            student.Address = value;
                            break;
                        case "HealthConditions":
                            student.HealthConditions = value;
                            break;
                        case "TaekwondoBeltRank":
                            student.TaekwondoRank = Util.GetTKDRank(value);
                            break;
                        case "JudoBeltRank":
                            student.JudoRank = Util.GetJudoRank(value);
                            break;
                        case "Medication":
                            student.Medication = value;
                            break;
                        case "Allergies":
                            student.Allergies = value;
                            break;
                        case "CourseType":
                            student.CourseType = value;
                            break;
                        case "CurrentStudent":
                            student.CurrentStudent = Boolean.Parse(value);
                            break;
                        case "MembershipExpiration":

HMAFlex/Controllers/CheckInController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HMAFlex.Controllers
{
    public class CheckInController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("loggedIn") != "false") {
                HttpContext.Session.SetString("loggedIn", "false");
                HttpContext.Session.SetString("loggedInUser", "");
            }

            int numAMPStudents = Program.AMPStudents.Count;
            int numAMPStaff = Program.AMPStaff.Count;
            int numSummerStudents = Program.SummerStudents.Count;
            int numSummerStaff = Program.SummerStaff.Count;
            int numEveningClass = Program.EveningClassStudents.Count;

            @ViewBag.numAMPStudent = numAMPStudents;
            @ViewBag.numAMPStaff = numAMPStaff;
            @ViewBag.numSummerStudent = numSummerStudents;
            @ViewBag.numSummerStaff = numSummerStaff;
            @ViewBag.numEveningClass = numEveningClass;
            
            return View();
        }
        
        public IActionResult SummerCamp()
        {
            if (HttpContext.Session.GetString("loggedIn") != "false") {
                HttpContext.Session.SetString("loggedIn", "false");
                HttpContext.Session.SetString("loggedInUser", "");
            }
            
            return View();
        }
        
        public IActionResult EveningClass()
        {
            if (HttpContext.Session.GetString("loggedIn") != "false") {
                HttpContext.Session.SetString("loggedIn", "false");
                HttpContext.Session.SetString("loggedInUser", "");
            }
            
            return View();
        }
        
        public IActionResult AMP()
        {
            if (HttpContext.Session.GetString("loggedIn") != "false") {
                HttpContext.Session.SetString("loggedIn", "false");
                HttpContext.Session.SetString("loggedInUser", "");
            }
            
            return View();
        }
    }
}

HMAFlex/Views/CheckIn/AMP.cshtml
@{
    ViewData["Title"] = "AMP Student Check-In";
    Layout = "_CheckInLayout";
}

<div class="col">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6">
                    
                </div>
                <div class="col-lg-6">
                    
                </div>
            </div>
        </div>
    </div>
</div>

HMAFlex/Views/CheckIn/EveningClass.cshtml
@{
    ViewData["Title"] = "Evening Class Student Check-In";
    Layout = "_CheckInLayout";
}

<div class="col">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6">
                    
                </div>
                <div class="col-lg-6">
                    
                </div>
            </div>
        </div>
    </div>
</div>

HMAFlex/Views/CheckIn/Index.cshtml
@using System.Xml
@using System.Collections
@using System.IO.Pipelines
@using HMAFlex.Controllers
@using HMAFlex.Models
@{
    ViewData["Title"] = "Check-In Landing Page";
	Layout = "_CheckInLayout";



	//CheckedIn Counts
	int numAmpStaff = 0;
	int numAmpStudents = 0;
	int numSummerStaff = 0;
	int numSummerStudents = 0;
	int numEveningClass = 0;

	foreach (var (key, value) in Program.CheckIns)
	{
		switch (value.Type)
		{
			case CheckInOutType.AMPStaff: numAmpStaff++; break;
			case CheckInOutType.AMPStudent: numAmpStudents++; break;
			case CheckInOutType.SummerStaff: numSummerStaff++; break;
			case CheckInOutType.SummerStudent: numSummerStudents++; break;
			case CheckInOutType.EveningClassStudent: numEveningClass++; break;
		}
	}
	foreach (var (key, value) in Program.CheckOuts)
	{
		switch (value.Type)
		{
			case CheckInOutType.AMPStaff: numAmpStaff--; break;
			case CheckInOutType.AMPStudent: numAmpStudents--; break;
			case CheckInOutType.SummerStaff: numSummerStaff--; break;
			case CheckInOutType.SummerStudent: numSummerStudents--; break;
			case CheckInOutType.EveningClassStudent: numEveningClass--; break;
		}
	}

	double percentAmpStaff = numAmpStaff / @ViewBag.numAMPStaff * 100;
	double percentAmpStudent = numAmpStudents / @ViewBag.numAMPStudent * 100;
	double percentSummerStaff = numSummerStaff / @ViewBag.numSummerStaff * 100;
	double percentSummerStudent = numSummerStudents / @ViewBag.numSummerStudent * 100;
	double percentEveningClass = numEveningClass / @ViewBag.numEveningClass * 100;
}

<link rel="stylesheet" href="css/ProgressBar.css">

<style>
	h4 {
		text-align:  center;
		padding-top: 2rem;
	}
	
	.p-5 {
		padding: 3rem 0 0 0 !important; /* top right bottom left */
	}
	
	a:link {
		text-decoration: none;
	}
</style>


<div class="card-body p-0">
	<!-- Nested Row within Card Body -->
	<div class="row">
		<!--
		AMP
		-->
		<div class="col-4">
			<div class="container p-5">
				<a role="button" asp-area="" asp-controller="CheckIn" asp-action="AMP">
					<div class="progress" data-percentage="@Convert.ToInt32(percentAmpStudent)">
						<span class="progress-left">
							<span class="progress-bar"></span>
						</span>
						<span class="progress-right">
							<span class="progress-bar"></span>
						</span>
						<div class="progress-value">
							<div>
								@numAmpStudents / @ViewBag.numAMPStudent (@Convert.ToInt32(percentAmpStudent)%)<br>
								<span>Checked In</span>
							</div>
						</div>
					</div>
				</a>
			</div>
			<h4>AMP Students</h4>
		</div>
		<div class="col-4">
			<div class="container p-5">
				<a role="button" asp-area="" asp-controller="CheckIn" asp-action="AMP">
					<div class="progress" data-percentage="@Convert.ToInt32(percentAmpStaff)">
						<span class="progress-left">
							<span class="progress-bar"></span>
						</span>
						<span class="progress-right">
							<span class="progress-bar"></span>
						</span>
						<div class="progress-value">
							<div>
								@numAmpStaff / @ViewBag.numAMPStaff (@Convert.ToInt32(percentAmpStaff)%)<br>
								<span>Checked In</span>
							</div>
						</div>
					</div>
				</a>
			</div>
			<h4>AMP Staff</h4>
		</div>

		<!--
		Information or something idk
		-->
		<div class="col-4">
			<div class="align-content-center" style="padding: 22% 5% 0 0;">
				<h1 style="text-align: center; color: #005894 !important; font-weight: bolder;">Student and Staff Check-In</h1>
				<h5 style="text-align: center;">Click on a circle to check-in/check-out a student.</h5>
			</div>
		</div>
				
	</div>
			
	<div class="row">
		<!--
		Summer Camp
		-->
		<div class="col-4">
			<div class="container p-5">
				<a role="button" asp-area="" asp-controller="CheckIn" asp-action="SummerCamp">
					<div class="progress" data-percentage="@Convert.ToInt32(percentSummerStudent)">
						<span class="progress-left">
							<span class="progress-bar"></span>
						</span>
						<span class="progress-right">
							<span class="progress-bar"></span>
						</span>
						<div class="progress-value">
							<div>
								@numSummerStudents / @ViewBag.numSummerStudent (@Convert.ToInt32(percentSummerStudent)%)<br>
								<span>Checked In</span>
							</div>
						</div>
					</div>
				</a>
			</div>
			<h4>Summer Camp Students</h4>
		</div>
		<div class="col-4">
			<div class="container p-5">
				<a role="button" asp-area="" asp-controller="CheckIn" asp-action="SummerCamp">
					<div class="progress" data-percentage="@Convert.ToInt32(percentSummerStaff)">
						<span class="progress-left">
							<span class="progress-bar"></span>
						</span>
						<span class="progress-right">
							<span class="progress-bar"></span>
						</span>
						<div class="progress-value">
							<div>
								@numSummerStaff / @ViewBag.numSummerStaff (@Convert.ToInt32(percentSummerStaff)%)<br>
								<span>Checked In</span>
							</div>
						</div>
					</div>
				</a>
			</div>
			<h4>Summer Camp Staff</h4>
		</div>
		<!--
		Evening Class
		-->
		<div class="col-4">
			<div class="container p-5">
				<a role="button" asp-area="" asp-controller="CheckIn" asp-action="EveningClass">
					<div class="progress" data-percentage="@Convert.ToInt32(percentEveningClass)">
						<span class="progress-left">
							<span class="progress-bar"></span>
						</span>
						<span class="progress-right">
							<span class="progress-bar"></span>
						</span>
						<div class="progress-value">
							<div>
								@numEveningClass / @ViewBag.numEveningClass (@Convert.ToInt32(percentEveningClass)%)<br>
								<span>Checked In</span>
							</div>
						</div>
					</div>
				</a>
			</div>
			<h4>Evening Class Students</h4>
		</div>
	</div>
</div>


<!--

	<div class="col-lg-6">
		<div class="container p-5">
			<div class="progress" data-percentage="55">
				<span class="progress-left">
					<span class="progress-bar"></span>
				</span>
				<span class="progress-right">
					<span class="progress-bar"></span>
				</span>
				<div class="progress-value">
					<div>
						55/100 (55%)<br>
						<span>completed</span>
					</div>
				</div>
			</div>
		</div>
	</div>

-->

HMAFlex/Views/CheckIn/SummerCamp.cshtml
@{
    ViewData["Title"] = "Summer Student Check-In";
    Layout = "_CheckInLayout";
}

<div class="col">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6">
                    
                </div>
                <div class="col-lg-6">
                    
                </div>
            </div>
        </div>
    </div>
</div>